# Generated by Django 6.0.6 on 2026-06-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'material_categories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(max_length=50)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_materials', to='materials.materialcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('qty_required', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_ordered', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_used', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_materials', to='materials.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_materials', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('qty_required', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_used', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_materials', to='materials.material')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_materials', to='projects.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
