# Generated by Django 6.0.6 on 2026-06-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialadditionaldetails',
            old_name='company_name',
            new_name='company',
        ),
    ]
