# Generated by Django 6.0.6 on 2026-06-29 09:19

import django.db.models.deletion
import django.db.models.manager
import mptt.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_rename_company_name_materialadditionaldetails_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], help_text='Type of account group for reporting (BS/PL).', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_control_account', models.BooleanField(default=False, help_text='Is this account a control account?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, default='', help_text='Unique ledger code.', max_length=100, unique=True)),
                ('reference_number', models.CharField(default='', help_text='Reference to entity in the system.', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=16)),
                ('postings_allowed', models.BooleanField(default=True, help_text='If false, posting to this account is restricted')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False, editable=False)),
                ('merged', models.BooleanField(default=False)),
                ('is_cash_account', models.BooleanField(default=False, help_text='Is this account a cash account?')),
                ('remarks', models.TextField(blank=True, default='', help_text='Remarks of the account.')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('material_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_account', to='materials.materialgroup')),
                ('merged_to', models.ForeignKey(blank=True, help_text="If merged, this account's data refers to another account.", null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.glaccount')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, help_text='Parent should be control account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.glaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
