# Generated by Django 6.0.6 on 2026-06-29 09:19

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glaccount',
            name='party_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_account', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='glaccountgroup',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent GL Account Group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.glaccountgroup'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='account_group',
            field=models.ForeignKey(help_text='GLAccountGroup ID.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.glaccountgroup'),
        ),
    ]
