# Generated by Django 6.0.6 on 2026-06-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glaccount',
            old_name='party_account',
            new_name='vendor_account',
        ),
    ]
