# Generated by Django 6.0.6 on 2026-06-21 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('pay_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], default='daily', max_length=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('overtime_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('extra_break_duration', models.DurationField(blank=True, null=True)),
                ('leave_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_attendance', to='manpower.worker')),
            ],
        ),
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
                ('attendance_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manpower.attendancelog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManpowerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('assigned_from', models.DateField()),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('incomplete', 'Incomplete')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_assignments', to='projects.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manpower.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='manpower.workercategory'),
        ),
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created_by', models.IntegerField(default=0, editable=False)),
                ('modified_by', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_bs', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'PC'), ('tablet', 'TABLET'), ('other', 'OTHER')], default='mobile', editable=False, help_text='Enum field for the device type.', max_length=10)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('ios', 'IOS'), ('android', 'ANDROID'), ('mac', 'MAC'), ('linux', 'LINUX'), ('other', 'OTHER')], default='other', editable=False, help_text='Enum field for the app type.', max_length=10)),
                ('document_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='worker_documents/')),
                ('document_no', models.CharField(blank=True, max_length=15, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_images', to='manpower.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(fields=('worker', 'work_date'), name='unique_worker_daily_attendance'),
        ),
    ]
