# Generated by Django 6.0.6 on 2026-06-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='group_of_worker',
            field=models.BooleanField(default=False, help_text='Indicates if this attendance log is for a group of workers (True)'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='total_workers',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Total number of workers present. Only applicable when group_of_worker is True.', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_attendance', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='worker',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='The vendor this worker belongs to. Null if independent worker.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_attendance', to='manpower.worker'),
        ),
    ]
