"""
Django settings for cms_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers
from decouple import config

from .db import DATABASE as DATABASES_
from .rest import REST_FRAMEWORK_CONFIGS
from .settings_config import (
    CONFIG_CORS_ALLOWED_ORIGINS,
    CONFIG_DEBUG,
    CONFIG_SECRET_KEY,
)
from .simple_jwt import SIMPLE_JWT_CONFIGS
from .spectacular import SPECTACULAR_SETTINGS_

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-m$t#f9=05k7nzy9=smv8&o#6j@wgt*l#islk@=-v3zqkix3lrf"

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = CONFIG_DEBUG

ALLOWED_HOSTS = ["*"]


DEBUG = CONFIG_DEBUG
SECRET_KEY = CONFIG_SECRET_KEY

# Application definition
DISABLED_AUTHENTICATION = config("DISABLED_AUTHENTICATION", cast=bool, default=False)


# Application definition
THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "rest_framework_simplejwt.token_blacklist",
    "django_user_agents",
]

LOCAL_APPS = [
    "apps.authentication",
    "apps.projects",
    "apps.materials",
    "apps.manpower",
    "apps.vendor",
    "apps.accounting",
    "apps.purchase",
]
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

INSTALLED_APPS += LOCAL_APPS
INSTALLED_APPS += THIRD_PARTY_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cms_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
ASGI_ENV = config("ASGI_ENV", cast=bool, default=True)

if ASGI_ENV:
    ASGI_APPLICATION = "cms_backend.asgi.application"
else:
    WSGI_APPLICATION = "cms_backend.wsgi.application"

DECIMAL_PLACES = config("DECIMAL_PLACES", cast=int, default=4)
MAX_DIGITS = config("MAX_DIGITS", cast=int, default=12)
MAX_DECIMAL_DIGITS = config("MAX_DECIMAL_DIGITS", cast=int, default=16)
# WSGI_APPLICATION = "cms_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = DATABASES_

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
if not os.path.exists(STATIC_ROOT):
    os.mkdir(STATIC_ROOT)

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


AUTH_USER_MODEL = "authentication.CustomUser"


APPEND_SLASH = False

SPECTACULAR_SETTINGS = SPECTACULAR_SETTINGS_

CORS_ALLOW_HEADERS = (
    *default_headers,
    "ngrok-skip-browser-warning",
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    cast=lambda v: [i.strip() for i in v.split(",") if i.strip()],  # ← add filter
    default="",
)


CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOWED_ORIGIN_REGEXES = [
    config("CORS_ALLOWED_ORIGIN_REGEXES", default=r"^https://.*\.ngrok-free\.dev$")
]
SIMPLE_JWT = SIMPLE_JWT_CONFIGS
REST_FRAMEWORK = REST_FRAMEWORK_CONFIGS
CORS_ALLOWED_ORIGINS = CONFIG_CORS_ALLOWED_ORIGINS
# env data for global settings
MAX_UPLOAD_SIZE = config("MAX_UPLOAD_SIZE", cast=int, default=2097152)
# MAX_COMPRESSED_IMAGE_SIZE = config(
#     "MAX_COMPRESSED_IMAGE_SIZE", cast=int, default=1048576
# )


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_PASSWORD = config("EMAIL_PASS", default="")
EMAIL_HOST_USER = config("EMAIL_USER", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="")

DATA_UPLOAD_MAX_MEMORY_SIZE = 25242880
if DEBUG:
    # MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    INSTALLED_APPS += [
        "debug_toolbar",
    ]

    INTERNAL_IPS = [
        "127.0.0.1",
        "localhost",
        "172.17.0.1",
    ]
    import mimetypes

    mimetypes.add_type("application/javascript", ".js", True)
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
        "DISABLE_PANELS": {
            "debug_toolbar.panels.redirects.RedirectsPanel",
            "debug_toolbar.panels.history.HistoryPanel",
            # Avoid cProfile conflicts in dev environments where another profiler is active.
            "debug_toolbar.panels.profiling.ProfilingPanel",
        },
        "SHOW_TEMPLATE_CONTEXT": True,
        # FIX: Render panels immediately to avoid AJAX loading issues
        "RENDER_PANELS": True,
        # FIX: Use local jQuery to prevent CDN timeout issues
        "JQUERY_URL": "",
    }
